[tool.poetry]
name = "cinema-project"
version = "0.1.0"
description = ""
authors = ["Laminatqw <victor.kinash47@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]

python = "^3.12"
isort = "^6.0.1"
django-dotenv = "^1.4.2"
djangorestframework =  "^3.14"
django-filter = "^25.1"
mysqlclient = "^2.2.7"
pillow = "^11.3.0"
djangorestframework-simplejwt = "^5.5.1"
django-qr-code = "^4.2.0"
qrcode = {extras = ["pil"], version = "^8.2"}
celery = "^5.5.3"
redis = "^6.4.0"
django-celery-results = "^2.6.0"
django = "^5.2.6"
beet = "^0.111.0"
django-celery-beat = "^2.8.1"
stripe = "^12.5.1"
drf-yasg = "^1.21.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
