# Generated by Django 5.2.5 on 2025-08-13 11:37

from django.db import migrations

import apps.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_profilemodel'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
