# Generated by Django 5.2.5 on 2025-08-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
        ('movies', '0002_remove_moviemodel_is_now_showing_moviemodel_end_date_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='halls.hallmodel'),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='movies.moviemodel'),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
