# Generated by Django 5.2.5 on 2025-09-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0002_sessionmodel_end_time_sessionmodel_hall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionmodel',
            name='price',
        ),
        migrations.AlterModelTable(
            name='sessionmodel',
            table='sessions',
        ),
        migrations.CreateModel(
            name='SessionPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vip_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sessions.sessionmodel')),
            ],
            options={
                'db_table': 'session_prices',
            },
        ),
    ]
