# Generated by Django 5.2.5 on 2025-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0003_remove_sessionmodel_price_alter_sessionmodel_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionpricemodel',
            name='vip_price',
        ),
        migrations.AddField(
            model_name='sessionpricemodel',
            name='seat_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('disabled', 'Accessible')], default='regular', max_length=20),
        ),
    ]
