# Generated by Django 5.2.5 on 2025-08-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
                ('hall_type', models.CharField(choices=[('standard', 'Standard'), ('imax', 'IMAX'), ('3d', '3D')], default='standard', max_length=50)),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='HallSeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('disabled', 'Accessible')], default='regular', max_length=20)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='halls.hallmodel')),
            ],
            options={
                'db_table': 'hall_seats',
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
    ]
