# Generated by Django 5.2.5 on 2025-08-26 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halls', '0001_initial'),
        ('sessions', '0002_sessionmodel_end_time_sessionmodel_hall_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='reserved', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='photo_storage/qr_codes/')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.hallseatmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.sessionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'unique_together': {('session', 'seat')},
            },
        ),
    ]
