# Generated by Django 5.2 on 2025-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('picture', models.ImageField(upload_to='movies/')),
                ('trailer_link', models.URLField()),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('is_now_showing', models.BooleanField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
