# Generated by Django 5.2.5 on 2025-08-13 11:37

from django.db import migrations, models

import apps.movies.services


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='is_now_showing',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='picture',
            field=models.ImageField(blank=True, upload_to=apps.movies.services.upload_poster),
        ),
    ]
