# Generated by Django 5.2.5 on 2025-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_moviemodel_is_now_showing_moviemodel_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='genre',
        ),
    ]
