# Generated by Django 5.2.5 on 2025-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genremodel_remove_moviemodel_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='movies.genremodel'),
        ),
    ]
