# Generated by Django 5.2.5 on 2025-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviemodel_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='genre_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
